version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: lhbffinance-postgres
    environment:
      POSTGRES_USER: lhbff_user
      POSTGRES_PASSWORD: lhbff_pass
      POSTGRES_DB: lhbff_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lhbff-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: lhbffinance-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/lhbff_db
      KC_DB_USERNAME: lhbff_user
      KC_DB_PASSWORD: lhbff_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - lhbff-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: lhbffinance-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - lhbff-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: lhbffinance-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - lhbff-net

volumes:
  postgres_data:

networks:
  lhbff-net:
    driver: bridge
